shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')
app_name = 'shop'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year, name='archives_year'),
    path('',views.item_list,name='item_list'),
    path('detail/<int:pk>/',views.item_detail,name='item_detail'),
    path('new/',views.item_new, name='item_new'),
    path('<int:pk>/edit/',views.item_edit, name='item_edit'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from first.utils import uuid_upload_to

class Item(models.Model):
    name = models.CharField(max_length=100, validators=[])
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo=models.ImageField(blank=True,upload_to=uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<{}> {}'.format(self.pk, self.name)

    def get_absolute_url(self):
        return reverse('shop:item_detail',args=[self.pk])
        return reverse('shop:item_detail',kwargs={'pk':self.pk})


shop/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model =Item
        fields='__all__'

shop/views.py
import logging
import re
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView,UpdateView
from .models import Item
from .forms import ItemForm

logger = logging.getLogger(__name__)  # __name__ => "shop.views"


def archives_year(request, year):
    return HttpResponse('{}년도에 대한 기록'.format(year))


def item_list(request):
    qs = Item.objects.all()
    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)
    logger.debug('query : {}'.format(q))
    return render(request, 'shop/item_list.html', {
        'item_list': qs,
        'q': q,
    })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html', {
        'item': item,
    })


#def item_new(request, item=None):
 #   if request.method == 'POST':
   #     form = ItemForm(request.POST, request.FILES,instance=item)
  #      if form.is_valid():
 #           form.save()
#            return redirect(item)
 #   else:
 #       form = ItemForm(instance=item)

#    return render(request, 'shop/item_form.html', {
#        'form': form,
#    })


#def item_edit(request, pk):
 #   item = get_object_or_404(Item, pk=pk)
  #  return item_new(request, item)

item_new= CreateView.as_view(model=Item, form_class=ItemForm)
item_edit= UpdateView.as_view(model=Item, form_class=ItemForm)

shop/templates/shop/item_detail.html
{% extends "shop/layout.html"%}
{%load humanize %}
    {% block content %}
        <h2>{{item.name}} </h2>

     {% if item.photo %}
            {{item.photo.url}}
     {% endif %}

            가격: {{item.price|intcomma}}원

                {% if item.desc %}
                    <p>
                        {{item.desc}}
                    </p>
                {% endif %}
                <hr/>
            <a href="{% url 'shop:item_list' %}">목록</a>
            <a href="{% url 'shop:item_edit' item.pk %}">수정</a>
    {% endblock %}


shop/templates/shop/item_list.html

{% extends "shop/layout.html"%}
    {% block content %}

        <form action="" method="GET">
            <input type="text" name="q" value="{{q}}"/>
            <input type="submit" value="search"/>


        </form>
        <ul>
            {% for item in item_list %}
                <li>
                    <a href="{{item.get_absolute_url}}">
                        {{item.name}}
                    </a>
                    {{item.price}}
                    {{item.desc}}
                </li>
            {% endfor %}
        </ul>

    <hr/>
    <a href="{%url 'shop:item' %}">New Item</a>

    {% endblock %}

shop/templates/shop/layout.html
{% extends "layout.html" %}
{%load fresh_static %}
{% block title %}Shop by escape room{% endblock %}

    {% block extra_head %}
        {{block.super}}
         <link rel="stylesheet" href="{% fresh_static 'shop/shop.css' %}" />
    {% endblock %}

    {% block extra_body %}
        {{block.super}}
    {% endblock %}